### ISSUE TITLE
Crash with NullPointer

### ISSUE THREAD

**Issue by raphaelquati** [sbaudoin/sonar-yaml#14]
```
3:05:53.693 DEBUG: Problems found: [1:31:wrong new line character: expected \n (new-lines)]
03:05:53.693 DEBUG: Creating violation for 1:31:wrong new line character: expected \n (new-lines)
03:05:53.693 DEBUG: Saving issue: trailing spaces (trailing-spaces)
03:05:53.693 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.693 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.693 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.693 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.693 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.693 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.693 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.693 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.693 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.693 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.693 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.693 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.708 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.708 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.708 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.708 DEBUG: Saving issue: too many spaces inside braces (braces)
03:05:53.708 DEBUG: Saving issue: missing document start "---" (document-start)
03:05:53.708 DEBUG: Saving issue: wrong new line character: expected \n (new-lines)
03:05:54.428 INFO: ------------------------------------------------------------------------
03:05:54.428 INFO: EXECUTION FAILURE
03:05:54.428 INFO: ------------------------------------------------------------------------
03:05:54.428 INFO: Total time: 1:09.213s
03:05:54.522 INFO: Final Memory: 17M/266M
03:05:54.522 INFO: ------------------------------------------------------------------------
##[error]03:05:54.522 ERROR: Error during SonarQube Scanner execution
##[debug]Processed: ##vso[task.logissue type=error;]03:05:54.522 ERROR: Error during SonarQube Scanner execution
03:05:54.522 ERROR: Error during SonarQube Scanner execution
##[error]java.lang.NullPointerException
	at org.sonar.scanner.report.ScannerReportUtils.toProtocolType(ScannerReportUtils.java:31)
	at org.sonar.scanner.sensor.DefaultSensorStorage.lambda$store$0(DefaultSensorStorage.java:445)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:447)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.doSave(DefaultHighlighting.java:121)
	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
	at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.saveSyntaxHighlighting(YamlSensor.java:184)
	at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.runChecks(YamlSensor.java:147)
	at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.execute(YamlSensor.java:97)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:408)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:403)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:400)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:360)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:126)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

**Comment by sbaudoin** [comment]
Indeed... But I need a bit more information:
* Can you tell me what version of sonar-yaml are you using?
* Can you tell me what version of Sonar scanner are you using?
* Can you give the YAML file that causes the issue?

Thanks

**Comment by raphaelquati** [comment]
Sonarqube version: 7.6
SonarYaml version: Last version available: 1.4.0
![image](https://user-images.githubusercontent.com/815086/52905793-708dd480-3226-11e9-9b5f-98f1cf793c89.png)
Sonar Scanner: Provided by VSTS (SonarScanner for MSBuild 4.5)

I don't know what file cause the error (yaml files generate by helm). But it shows syntax errors on this template files:
![image](https://user-images.githubusercontent.com/815086/52905907-91efc000-3228-11e9-90c1-0ac6628b067d.png)

hpa.yaml
```
{{- if .Values.hpa.enabled -}}
{{- $fullName := include "aaa.fullname" . -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "aaa.name" . }}
    chart: {{ template "aaa.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ $fullName }}
{{- with .Values.hpa.metrics }}
  metrics:  
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}

```

**Comment by saily** [comment]
I had the same issue when yaml plugin did report too many issues. By attaching `--debug` flag i was able to figure out that the yaml plugin was responsible for raising the `NullPointerException`. 

I'm using SonarQube v6.7.6 and v1.4.0 of the yaml plugin.

**Comment by andy812** [comment]
I had the same issue when i scanned encrypted yaml (i use [ansible-vault)](https://docs.ansible.com/ansible/2.4/vault.html)
