### ISSUE TITLE
SonarQube 6.7 LTS: Crash in analysis using Windows SonarQube Scanner

### ISSUE THREAD

**Issue by alixwar** [sbaudoin/sonar-yaml#26]
Plugin version: 1.4.2

```
16:47:04.668 ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
        at java.util.regex.Pattern.<init>(Pattern.java:1350)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at java.util.regex.Pattern.matches(Pattern.java:1133)
        at java.lang.String.matches(String.java:2121)
        at com.github.sbaudoin.sonar.plugins.yaml.checks.ForbiddenCheck.validate(ForbiddenCheck.java:57)
        at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.runChecks(YamlSensor.java:149)
        at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.execute(YamlSensor.java:103)
```

**Comment by sbaudoin** [comment]
Well... May you give some more details, please? With so little info I'd say the problem is located in your configuration of the forbidden key rule. So can you provide the configuration of the forbidden key check and the YAML you are trying to analyze please?

**Comment by alixwar** [comment]
Hi @sbaudoin 
Sure, what details do you want?
Running the SonarQube scanner for linux works fine so I'd say it's either this plugin or the SonarQube windows scanner that is causing issues.

This is all the details I have (with -X flag) for the broken build:

```
10:54:07.258 DEBUG: YAMLLint config for rule yaml:LineLengthCheck/line-length: '---
rules:
  line-length:
    max: 80
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: false
'
10:54:07.282 DEBUG: Problems found: [21:81:line too long (119 > 80 characters) (line-length), 24:81:line too long (219 > 80 characters) (line-length), 34:81:line too long (84 > 80 characters) (line-length)]
10:54:07.283 DEBUG: Creating violation for 21:81:line too long (119 > 80 characters) (line-length)
10:54:07.284 DEBUG: Creating violation for 24:81:line too long (219 > 80 characters) (line-length)
10:54:07.285 DEBUG: Creating violation for 34:81:line too long (84 > 80 characters) (line-length)
10:54:07.285 DEBUG: Checking rule: yaml:ForbiddenValueCheck
10:54:07.351 INFO: ------------------------------------------------------------------------
10:54:07.351 INFO: EXECUTION FAILURE
10:54:07.352 INFO: ------------------------------------------------------------------------
10:54:07.352 INFO: Total time: 40.697s
10:54:07.458 INFO: Final Memory: 42M/1449M
10:54:07.458 INFO: ------------------------------------------------------------------------
10:54:07.459 ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
        at java.util.regex.Pattern.<init>(Pattern.java:1350)
        at java.util.regex.Pattern.compile(Pattern.java:1028)
        at java.util.regex.Pattern.matches(Pattern.java:1133)
        at java.lang.String.matches(String.java:2121)
        at com.github.sbaudoin.sonar.plugins.yaml.checks.ForbiddenCheck.validate(ForbiddenCheck.java:57)
        at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.runChecks(YamlSensor.java:149)
        at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.execute(YamlSensor.java:103)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
        at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
        at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
        at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:177)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:291)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:286)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:264)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
        at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
        at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
        at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

This is the config for the rule:

allow-non-breakable-inline-mappings: false
allow-non-breakable-words: true
max: 80

**Comment by sbaudoin** [comment]
Thanks for the details. allow-non-breakable-inline-mappings, etc. are the settings for the LineLengthCheck rule. The settings for the ForbiddenValueCheck rule are `key-name` and `value` that are regular expressions used to identified the key/value pair to be forbidden. So can you give the values you set for these parameters as well as the YAML you are checking, please?

From what I saw and tested, such an error occurs when you do not supply a value for the `key-name` parameter. As said in the documentation if you want to match any key (meaning that you want to completely forbid a value anywhere in you YAML file) use `.*` as the value for the `key-name` parameter.

**Comment by alixwar** [comment]
@sbaudoin Ah. It is a rule template... I have actually not set it at all (but enabled it) which is probably why it fails. Thanks. I think we can close this ticket. I'll reopen it if it's still an issue after it's been configured.

**Comment by alixwar** [comment]
A comment: Strange that the analysis worked fine using the linux sonarqube scanner. Might be an issue there to look into

**Comment by alixwar** [comment]
But maybe the strangest thing is that I could enabled the "rule" through the Web Service API

**Comment by sbaudoin** [comment]
Yes indeed, it's strange. I have not tried this use case, I tried only via the Web UI.
