### ISSUE TITLE
sonar-yaml 1.8.0 fails on k8s YAML files (Trying to save highlighting twice)

### ISSUE THREAD

**Issue by thomasgl-orange** [sbaudoin/sonar-yaml#86]
With `sonar-yaml` 1.8.0, in a project which contains k8s YAML files, analysis fails with the following exception:
```
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 15.860s
INFO: Final Memory: 39M/148M
INFO: ------------------------------------------------------------------------
ERROR: Error during SonarScanner execution
java.lang.UnsupportedOperationException: Trying to save highlighting twice for the same file is not supported: k8s.yml
	at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:303)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.doSave(DefaultHighlighting.java:109)
	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
	at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.saveSyntaxHighlighting(YamlSensor.java:314)
	at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.execute(YamlSensor.java:120)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
```
(that's easy to reproduce with a single file, mine is the example from [S6428](https://sqaas.dos.tech.orange/coding_rules?languages=kubernetes&open=kubernetes%3AS6428))

Before 1.8.0, `sonar-yaml` was failing already, except a bit earlier, on this other conflict which is now catched and turned into a warning (#70):
```
INFO: Sensor YAML Sensor [yaml]
WARN: Cannot save measures for file k8s.yml, ignoring them
java.lang.UnsupportedOperationException: Can not add the same measure twice on k8s.yml: DefaultMeasure[component=k8s.yml,metric=Metric[uuid=<null>,key=ncloc_data,description=<null>,type=DATA,direction=0,domain=<null>,name=ncloc_data,qualitative=false,userManaged=false,enabled=true,worstValue=<null>,bestValue=<null>,optimizedBestValue=false,hidden=false,deleteHistoricalData=false,decimalScale=<null>],value=1=1;2=1;3=1;4=1;5=1;6=1;7=1;8=1;9=1;10=1;11=1;12=1;13=1;14=1,fromCore=false,storage=org.sonar.scanner.sensor.DefaultSensorStorage@4785f176,saved=false]
	at org.sonar.scanner.sensor.DefaultSensorStorage.saveMeasure(DefaultSensorStorage.java:179)
	at org.sonar.scanner.sensor.DefaultSensorStorage.store(DefaultSensorStorage.java:139)
	at org.sonar.api.batch.sensor.measure.internal.DefaultMeasure.doSave(DefaultMeasure.java:96)
	at org.sonar.api.batch.sensor.internal.DefaultStorable.save(DefaultStorable.java:45)
	at org.sonar.scanner.DefaultFileLinesContext.save(DefaultFileLinesContext.java:97)
	at com.github.sbaudoin.sonar.plugins.yaml.linecounter.LineCounter.saveMeasures(LineCounter.java:78)
	at com.github.sbaudoin.sonar.plugins.yaml.linecounter.LineCounter.analyse(LineCounter.java:56)
	at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.computeLinesMeasures(YamlSensor.java:158)
	at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.execute(YamlSensor.java:119)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
```

I will propose a merge-request to:
- similarly catch the `UnsupportedOperationException: Trying to save highlighting twice` and continue despite the error, not saving highlighting
- add a k8s YAML file to integration tests (generates 2 warnings in the scanner log, which are expected and thus ignored)
- be less verbose on the `WARN: Cannot save measures for...` (only print full exception if in debug mode, otherwise it becomes noisy/scary when analysing a project with many such errors)

**Comment by robross0606** [comment]
Why do we not see 1.8.1 or 1.9.0 in the Sonar Marketplace for plugin updating?

**Comment by sbaudoin** [comment]
Publication in the marketplace is a long process. They requested me to make several changes but as in the meantime I published some other versions, they eventually requested me to remove the 1.8.1 and 1.9.0 versions from the marketplace, and this change has still not been published (with the Christmas break I believe this is normal). I've just requested a review (again), hopping this will be published soon. I know this is not the best but you can [download the  JAR from GitHub](/sbaudoin/sonar-yaml/tags).

**Comment by jborgers** [comment]
Hi Sylvain,

Did you see my PR? Can you have a look?

Regards, Jeroen

Op za 30 dec 2023 om 20:43 schreef sbaudoin ***@***.***>:

**Comment by jborgers** [comment]
Hi Sylvain,

Please have a look at the PR.

Maybe you can give me more rights as a contributor?
So we can speed things up a bit?

Regards,
Jeroen

Op do 1 feb 2024 om 09:28 schreef Jeroen Borgers ***@***.***>:
