### ISSUE TITLE
StringIndexOutOfBoundsException in LineLength.check

### ISSUE THREAD

**Issue by jborgers** [sbaudoin/sonar-yaml#95]
We use plugin version 1.8.1 in SonarQube 9.8. An exception occurs resulting in a sonar scan failure:

```
2023-11-27T09:04:08.3693883Z INFO: Sensor Text Sensor [text]
2023-11-27T09:04:08.3727222Z INFO: 78 source files to be analyzed
2023-11-27T09:04:08.7588640Z INFO: 78/78 source files have been analyzed
2023-11-27T09:04:08.7589424Z INFO: Sensor Text Sensor [text] (done) | time=390ms
2023-11-27T09:04:08.7589952Z INFO: Sensor YAML Sensor [yaml]
2023-11-27T09:04:13.6430013Z INFO: ------------------------------------------------------------------------
2023-11-27T09:04:13.6431107Z INFO: EXECUTION FAILURE
2023-11-27T09:04:13.6431686Z INFO: ------------------------------------------------------------------------
2023-11-27T09:04:13.6432247Z INFO: Total time: 15.661s
2023-11-27T09:04:13.7043887Z INFO: Final Memory: 34M/124M
2023-11-27T09:04:13.7045437Z INFO: ------------------------------------------------------------------------
2023-11-27T09:04:13.7112783Z ##[error]ERROR: Error during SonarScanner execution
java.lang.StringIndexOutOfBoundsException: begin 1135, end 1134, length 23043
2023-11-27T09:04:13.7126474Z ERROR: Error during SonarScanner execution
2023-11-27T09:04:13.7127186Z java.lang.StringIndexOutOfBoundsException: begin 1135, end 1134, length 23043
2023-11-27T09:04:13.7129660Z ##[error]at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
at java.base/java.lang.String.substring(String.java:1874)
2023-11-27T09:04:13.7131704Z at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
2023-11-27T09:04:13.7139486Z ##[error]at com.github.sbaudoin.yamllint.rules.LineLength.check(LineLength.java:130)
at com.github.sbaudoin.yamllint.Linter.getCosmeticProblems(Linter.java:448)
at com.github.sbaudoin.sonar.plugins.yaml.checks.YamlLintCheck.validate(YamlLintCheck.java:47)
at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.runChecks(YamlSensor.java:193)
at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.execute(YamlSensor.java:131)
at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
2023-11-27T09:04:13.7143957Z
2023-11-27T09:04:13.7144412Z at com.github.sbaudoin.yamllint.rules.LineLength.check(LineLength.java:130)
2023-11-27T09:04:13.7145299Z at com.github.sbaudoin.yamllint.Linter.getCosmeticProblems(Linter.java:448)
2023-11-27T09:04:13.7146335Z at com.github.sbaudoin.sonar.plugins.yaml.checks.YamlLintCheck.validate(YamlLintCheck.java:47)
2023-11-27T09:04:13.7147469Z at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.runChecks(YamlSensor.java:193)
2023-11-27T09:04:13.7148558Z at com.github.sbaudoin.sonar.plugins.yaml.rules.YamlSensor.execute(YamlSensor.java:131)
2023-11-27T09:04:13.7149630Z at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:64)
2023-11-27T09:04:13.7156941Z ##[error]at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
at org.sonar.scanner.scan.SpringModuleScanContainer.doAfterStart(SpringModuleScanContainer.java:82)
2023-11-27T09:04:13.7162092Z at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:88)
2023-11-27T09:04:13.7163249Z at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:61)
2023-11-27T09:04:13.7164477Z at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:79)
2023-11-27T09:04:13.7165843Z at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:61)
2023-11-27T09:04:13.7172128Z ##[error]at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
at org.sonar.scanner.scan.SpringProjectScanContainer.scan(SpringProjectScanContainer.java:401)
at org.sonar.scanner.scan.SpringProjectScanContainer.scanRecursively(SpringProjectScanContainer.java:397)
```
[././.]
```
2023-11-27T09:04:13.7235531Z at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
2023-11-27T09:04:13.7236150Z at org.sonarsource.scanner.cli.Main.main(Main.java:62)
2023-11-27T09:04:13.7237452Z ##[error]ERROR:
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
2023-11-27T09:04:13.7238804Z ERROR:
2023-11-27T09:04:13.7239488Z ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
2023-11-27T09:04:14.0521795Z ##[error]The process '/agent/_work/_tasks/SonarQubeAnalyze_6d01813a-9589-4b15-8491-8164aeb38055/4.36.0/sonar-scanner/bin/sonar-scanner' failed with exit code 1
2023-11-27T09:04:14.0544923Z ##[section]Finishing: Run Code Analysis
```

**Comment by jborgers** [comment]
This seems like a bug. In addition, I think that the exception shopuld not result in a sonar scan failure, rather in skipping the file which caused the problem, and logging the stack trace, with an error or warning.

**Comment by jborgers** [comment]
There is only one substring() call in LineLength.check. 
From log: `StringIndexOutOfBoundsException: begin 1135, end 1134, length 23043`
So, `start` exceeds `line.end` which can be the case when `start` skips `line.end`. 
This can happen in line 139: `start += 2;`.

So, solve this by:
1. add condition to the if: 
`if (start < line.getEnd() && line.getBuffer().substring...) {`
2. change the enclosing if to:
`if (start < line.getEnd()) {`

**Comment by jborgers** [comment]
This logic happens within:
`if ((boolean)conf.get(OPTION_ALLOW_NON_BREAKABLE_WORDS)) {`
So, it seems that we can avoid it by setting that property to 'false'.

**Comment by sbaudoin** [comment]
Hello,

Thanks for reporting and giving the details, I'll try fix that shortly.

Sylvain

**Comment by sbaudoin** [comment]
@jborgers Do you have an example of code and configuration so that I can reproduce the issue, please?

**Comment by sbaudoin** [comment]
@jborgers never mind, got it
